/**********************************************************************
 * Copyright (c) by Heiner Jostkleigrewe
 * This program is free software: you can redistribute it and/or modify it under the terms of the 
 * GNU General Public License as published by the Free Software Foundation, either version 3 of the 
 * License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,  but WITHOUT ANY WARRANTY; without 
 *  even the implied warranty of  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See 
 *  the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program.  If not, 
 * see <http://www.gnu.org/licenses/>.
 * 
 * heiner@jverein.de
 * www.jverein.de
 **********************************************************************/
package de.jost_net.JVerein.keys;

public enum VorlageTyp
{
  // Dateinamen
  MITGLIEDER_DATEINAME("mitglieder-dateiname", "Mitglieder Dateiname",
      "Mitglieder-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  NICHT_MITGLIEDER_DATEINAME("nichtmitglieder-dateiname",
      "Nicht-Miglieder Dateiname",
      "Nicht-Miglieder-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  MITGLIED_ZUSATZBETRAEGE_DATEINAME("mitglieder-zusatzbetraege-dateiname",
      "Mitglieder Zusatzbeträge Dateiname",
      "Zusatzbeträge-$mitglied_vorname-$mitglied_name-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  MITGLIED_WIEDERVORLAGEN_DATEINAME("mitglieder-wiedervorlagen-dateiname",
      "Mitglieder Wiedervorlagen Dateiname",
      "Wiedervorlagen-$mitglied_vorname-$mitglied_name-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  MITGLIED_MAILS_DATEINAME("mitglieder-mails-dateiname",
      "Mitglieder Mails Dateiname",
      "Mails-$mitglied_vorname-$mitglied_name-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  MITGLIED_LEHRGAENGE_DATEINAME("mitglieder-lehrgaenge-dateiname",
      "Mitglieder Lehrgänge Dateiname",
      "Lehrgänge-$mitglied_vorname-$mitglied_name-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  MITGLIED_LESEFELDER_DATEINAME("mitglieder-lesefelder-dateiname",
      "Mitglieder Lesefelder Dateiname",
      "Lesefelder-$mitglied_vorname-$mitglied_name-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  MITGLIED_ARBEITSEINSAETZE_DATEINAME("mitglieder-arbeitseinsaetze-dateiname",
      "Mitglieder Arbeitseinsätze Dateiname",
      "Arbeitseinsätze-$mitglied_vorname-$mitglied_name-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  MITGLIED_DOKUMENTE_DATEINAME("mitglieder-dokumente-dateiname",
      "Mitglieder Dokumente Dateiname",
      "Dokumente-$mitglied_vorname-$mitglied_name-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  SPENDENBESCHEINIGUNG_DATEINAME("spendenbescheinigung-dateiname",
      "Spendenbescheinigung Dateiname",
      "Spendenbescheinigung-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  SPENDENBESCHEINIGUNG_MITGLIED_DATEINAME(
      "spendenbescheinigung-mitglied-dateiname",
      "Spendenbescheinigung-Mitglied Dateiname",
      "Spendenbescheinigung-$spendenbescheinigung_spendedatum_erstes-$spendenbescheinigung_zeile2",
      Vorlageart.DATEINAME.getKey()),
  RECHNUNG_DATEINAME("rechnung-dateiname", "Rechnung Dateiname",
      "Rechnung-$aktuellesdatum-$aktuellezeit", Vorlageart.DATEINAME.getKey()),
  RECHNUNG_MITGLIED_DATEINAME("rechnung-mitglied-dateiname",
      "Rechnung-Mitglied Dateiname",
      "Rechnung-$rechnung_nummer-$mitglied_name-$mitglied_vorname",
      Vorlageart.DATEINAME.getKey()),
  MAHNUNG_DATEINAME("mahnung-dateiname", "Mahnung Dateiname",
      "Mahnung-$aktuellesdatum-$aktuellezeit", Vorlageart.DATEINAME.getKey()),
  MAHNUNG_MITGLIED_DATEINAME("mahnung-mitglied-dateiname",
      "Mahnung-Mitglied Dateiname",
      "Mahnung-$rechnung_nummer-$mitglied_name-$mitglied_vorname",
      Vorlageart.DATEINAME.getKey()),
  KONTOAUSZUG_DATEINAME("kontoauszug-dateiname", "Kontoauszug Dateiname",
      "Kontoauszug-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  KONTOAUSZUG_MITGLIED_DATEINAME("kontoauszug-mitglied-dateiname",
      "Kontoauszug-Mitglied Dateiname",
      "Kontoauszug-$mitglied_name-$mitglied_vorname-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  FREIES_FORMULAR_DATEINAME("freies-formular-dateiname",
      "FreiesFormular Dateiname",
      "$formular_name-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  FREIES_FORMULAR_MITGLIED_DATEINAME("freies-formular-mitglied-dateiname",
      "FreiesFormular-Mitglied Dateiname",
      "$formular_name-$mitglied_name-$mitglied_vorname-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  CT1_AUSGABE_DATEINAME("1ct-ausgabe-dateiname", "1ctAusgabe Dateiname",
      "1ctueberweisung-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  GUTSCHRIFT_DATEINAME("gutschrift-dateiname", "Gutschrift Dateiname",
      "Gutschrift-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  PRENOTIFICATION_DATEINAME("pre-notification-dateiname",
      "Pre-Notification Dateiname",
      "Prenotification-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  PRENOTIFICATION_MITGLIED_DATEINAME("pre-notification-mitglied-dateiname",
      "Pre-Notification-Mitglied Dateiname",
      "Prenotification-$mitglied_name-$mitglied_vorname-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  PRENOTIFICATION_KURSTEILNEHMER_DATEINAME(
      "pre-notification-kursteilnehmer-dateiname",
      "Pre-Notification-Kursteilnehmer Dateiname",
      "Prenotification-$lastschrift_name-$lastschrift_vorname-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  ABWEICHENDE_ZAHLER_DATEINAME("abweichende-zahler-dateiname",
      "Abweichende Zahler Dateiname",
      "Abweichende-Zahler-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  FAMILIENVERBAND_DATEINAME("familienverband-dateiname",
      "Familienverband Dateiname",
      "Familienverband-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),

  // Reports aus Mitglieder
  PERSONALBOGEN_DATEINAME("personalbogen-dateiname", "Personalbogen Dateiname",
      "Personalbogen-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  PERSONALBOGEN_MITGLIED_DATEINAME("personalbogen-mitglied-dateiname",
      "Personalbogen-Mitglied Dateiname",
      "Personalbogen-$mitglied_name-$mitglied_vorname-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  VCARD_DATEINAME("vcard-dateiname", "VCard Dateiname",
      "VCards-$aktuellesdatum-$aktuellezeit", Vorlageart.DATEINAME.getKey()),
  VCARD_MITGLIED_DATEINAME("vcard-mitglied-dateiname",
      "VCARD-Mitglied Dateiname",
      "VCard-$mitglied_name-$mitglied_vorname-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  SOLLBUCHUNGEN_DATEINAME("sollbuchungen-dateiname",
      "Sollbuchungen Liste Dateiname",
      "Sollbuchungen-Differenz-$filter_differenz-$filter_datum_von_f-$filter_datum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  SPENDENBESCHEINIGUNGEN_DATEINAME("spendenbescheinigungen-dateiname",
      "Spendenbescheinigungen Liste Dateiname",
      "Spendenbescheinigungen-$filter_spendeart-$aktuellesdatum",
      Vorlageart.DATEINAME.getKey()),
  ARBEITSEINSAETZE_DATEINAME("arbeitseinsaetze-dateiname",
      "Arbeitseinsätze Dateiname",
      "Arbeitseinsätze-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  ZUSATZBETRAEGE_VORLAGEN_DATEINAME("zusatzbetraege-vorlagen-dateiname",
      "Zusatzbeträge Vorlagen Dateiname",
      "Zusatzbeträge-Vorlagen-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  ZUSATZBETRAEGE_DATEINAME("zusatzbetraege-dateiname",
      "Zusatzbeträge Liste Dateiname",
      "Zusatzbetraege-$filter_ausfuehrungstag-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  LEHRGAENGE_DATEINAME("lehrgaenge-dateiname", "Lehrgänge Dateiname",
      "Lehrgänge-$aktuellesdatum-$aktuellezeit", Vorlageart.DATEINAME.getKey()),
  KURSTEILNEHMER_DATEINAME("kursteilnehmer-dateiname",
      "Kursteilnehmer Dateiname",
      "Kursteilnehmer-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  RECHNUNGEN_DATEINAME("rechnungen-dateiname", "Rechnungen Dateiname",
      "Rechnungen-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  WIEDERVORLAGEN_DATEINAME("wiedervorlagen-dateiname",
      "Wiedervorlagen Dateiname",
      "Wiedervorlagen-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),

  // Reports aus Buchführung
  KONTEN_DATEINAME("konten-dateiname", "Konten Dateiname",
      "Konten-$aktuellesdatum-$aktuellezeit", Vorlageart.DATEINAME.getKey()),
  ANFANGSBESTAENDE_DATEINAME("anfangsbestaende-dateiname",
      "Anfangsbestände Dateiname",
      "Anfangsbestände-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  KONTENSALDO_DATEINAME("kontensaldo-dateiname", "Kontensaldo Dateiname",
      "Kontensdaldo-$zeitraum_von_f-$zeitraum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  BUCHUNGSJOURNAL_DATEINAME("buchungsjournal-dateiname",
      "Buchungsjournal Dateiname",
      "Buchungsjournal-$filter_datum_von_f-$filter_datum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  EINZELBUCHUNGEN_DATEINAME("einzelbuchungen-dateiname",
      "Einzelbuchungen Dateiname",
      "Buchungsliste-$filter_datum_von_f-$filter_datum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  CSVBUCHUNGEN_DATEINAME("csvbuchungen-dateiname",
      "CSVEinzelbuchungen Dateiname",
      "Buchungsliste-$filter_datum_von_f-$filter_datum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  SUMMENBUCHUNGEN_DATEINAME("summenbuchungen-dateiname",
      "Summenbuchungen Dateiname",
      "Summenliste-$filter_datum_von_f-$filter_datum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  BUCHUNGEN_DATEINAME("buchungen-dateiname", "Buchungen Dateiname",
      "Buchungen-$aktuellesdatum-$aktuellezeit", Vorlageart.DATEINAME.getKey()),
  ANLAGEN_BUCHUNGSJOURNAL_DATEINAME("anlagen-buchungsjournal-dateiname",
      "Anlagen Buchungsjournal Dateiname",
      "Anlagen-Buchungsjournal-$filter_datum_von_f-$filter_datum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  ANLAGEN_EINZELBUCHUNGEN_DATEINAME("anlagen-einzelbuchungen-dateiname",
      "Anlagen Einzelbuchungen Dateiname",
      "Anlagen-Buchungsliste-$filter_datum_von_f-$filter_datum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  ANLAGEN_CSVBUCHUNGEN_DATEINAME("anlagen-csvbuchungen-dateiname",
      "AnlagenCSVEinzelbuchungen Dateiname",
      "Anlagen-Buchungsliste-$filter_datum_von_f-$filter_datum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  ANLAGEN_SUMMENBUCHUNGEN_DATEINAME("anlagen-summenbuchungen-dateiname",
      "Anlagen Summenbuchungen Dateiname",
      "Anlagen-Summenliste-$filter_datum_von_f-$filter_datum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  ANLAGEN_BUCHUNGEN_DATEINAME("anlagen-buchungen-dateiname",
      "Anlagen Buchungen Dateiname",
      "Anlagen-Buchungen-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  BUCHUNGSKLASSENSALDO_DATEINAME("buchungsklassensaldo-dateiname",
      "Buchungsklassensaldo Dateiname",
      "Buchungsklassensaldo-$zeitraum_von_f-$zeitraum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  UMSATZSTEUER_VORANMELDUNG_DATEINAME("umsatzsteuervoranmeldung-dateiname",
      "Umsatzsteuer Voranmeldung Dateiname",
      "Umsatzsteuer-Voranmeldung-$zeitraum_von_f-$zeitraum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  PROJEKTSALDO_DATEINAME("projektsaldo-dateiname", "Projektsaldo Dateiname",
      "Projektsaldo-$zeitraum_von_f-$zeitraum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  ANLAGENVERZEICHNIS_DATEINAME("anlagenverzeichnis-dateiname",
      "Anlagenverzeichnis Dateiname",
      "Anlagenverzeichnis-$zeitraum_jahr-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  MITTELVERWENDUNGSREPORT_ZUFLUSS_DATEINAME(
      "mittelverwendung-zufluss-dateiname",
      "Mittelverwendung Zuflussreport Dateiname",
      "Mittelverwendung-Zufluss-$zeitraum_jahr-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  MITTELVERWENDUNGSREPORT_SALDO_DATEINAME("mittelverwendung-saldo-dateiname",
      "Mittelverwendung Saldoreport Dateiname",
      "Mittelverwendung-Saldo-$zeitraum_jahr-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  MITTELVERWENDUNGSSALDO_DATEINAME("mittelverwendungssaldo-dateiname",
      "Mittelverwendungssaldo Dateiname",
      "Mittelverwendungssaldo-$zeitraum_von_f-$zeitraum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  WIRTSCHAFTSPLAN_DATEINAME("wirtschaftsplan-dateiname",
      "Wirtschaftsplan Dateiname",
      "Wirtschaftsplan-$parameter_bezeichnung-$parameter_datum_von_f-$parameter_datum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  WIRTSCHAFTSPLAN_MEHRERE_DATEINAME("wirtschaftsplan-mehrere-dateiname",
      "Wirtschaftsplan Dateiname (Mehrere Pläne)",
      "Wirtschaftsplan-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  JAHRESABSCHLUESSE_DATEINAME("jahresabschluesse-dateiname",
      "Jahresabschlüsse Dateiname",
      "Jahresabschlüsse-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  JAHRESABSCHLUSS_DATEINAME("jahresabschluss-dateiname",
      "Jahresabschluss Dateiname",
      "Jahresabschluss-$filter_datum_von_f-$filter_datum_bis_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  WIRTSCHAFTSPLAENE_DATEINAME("wirtschaftsplaene-dateiname",
      "Wirtschaftspläne Dateiname",
      "Wirtschaftspläne-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),

  // Reports aus Abrechnung
  ABRECHNUNGSLAUF_LASTSCHRIFTEN_DATEINAME(
      "abrechnungslauf-lastschriften-dateiname",
      "Abrechnungslauf SEPAPDF-Lastschriften Dateiname",
      "Lastschriften-$parameter_faelligkeit_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  ABRECHNUNGSLAUF_LASTSCHRIFTEN2_DATEINAME(
      "abrechnungslauf-lastschriften2-dateiname",
      "Abrechnungslauf Lastschriften Dateiname",
      "Abrechnungslauf-Lastschriften-$parameter_lauf-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  ABRECHNUNGSLAUF_ZUSATZBETRAEGE_DATEINAME(
      "abrechnungslauf-zusatzbetraege-dateiname",
      "Abrechnungslauf Zusatzbeträge Dateiname",
      "Abrechnungslauf-Zusatzbeträge-$parameter_lauf-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  ABRECHNUNGSLAUF_SEPA_DATEINAME("abrechnungslauf-sepa-xml-dateiname",
      "Abrechnungslauf SEPAXML-Lastschriften Dateiname",
      "SEPA-Lastschriften-$parameter_faelligkeit_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  ABRECHNUNGSLAUF_SOLLBUCHUNGEN_DATEINAME("abrechnungslaufliste-dateiname",
      "Abrechnungslauf Sollbuchungen Dateiname",
      "Abrechnungslauf-Sollbuchungen-$parameter_lauf-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  ABRECHNUNGSLAUF_BUCHUNGEN_DATEINAME("abrechnungslauf-buchungen-dateiname",
      "Abrechnungslauf Buchungen Dateiname",
      "Abrechnungslauf-Buchungen-$parameter_lauf-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  ABRECHNUNGSLAEUFE_DATEINAME("abrechnungslaeufe-dateiname",
      "Abrechnungsläufe Dateiname",
      "Abrechnungsläufe-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  LASTSCHRIFTEN_DATEINAME("lastschriften-dateiname", "Lastschriften Dateiname",
      "Lastschriften-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),

  // Reports Druck und Mail
  MAILS_DATEINAME("mails-dateiname", "Mails Dateiname",
      "Mails-$aktuellesdatum-$aktuellezeit", Vorlageart.DATEINAME.getKey()),
  MAILVORLAGEN_DATEINAME("mailvorlagen-dateiname", "Mailvorlagen Dateiname",
      "Mailvorlagen-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),

  // Reports aus Auswertung
  AUSWERTUNG_MITGLIED_DATEINAME("auswertung-mitglied-dateiname",
      "Auswertung Mitglied Dateiname",
      "Mitglieder-$ausgabe_ausgabe-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  AUSWERTUNG_NICHT_MITGLIED_DATEINAME("auswertung-nichtmitglied-dateiname",
      "Auswertung Nicht-Mitglied Dateiname",
      "Nicht-Mitglieder-$ausgabe_ausgabe-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  AUSWERTUNG_ALTERSJUBILARE_DATEINAME("auswertung-altersjubilare-dateiname",
      "Auswertung Altersjubiläen Dateiname",
      "Altersjubilare-$filter_jahr-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  AUSWERTUNG_MITGLIEDSCHAFTSJUBILARE_DATEINAME(
      "auswertung-mitgliedsschaftsjubilare-dateiname",
      "Auswertung Mitgliedschaftsjubiläen Dateiname",
      "Mitgliedschaftsjubilare-$filter_jahr-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  AUSWERTUNG_MITGLIEDER_STATISTIK_DATEINAME(
      "auswertung-mitgliederstatistik-dateiname",
      "Auswertung Mitgliederstatistik Dateiname",
      "Mitgliederstatistik-$filter_stichtag_f-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  AUSWERTUNG_JAHRGANGS_STATISTIK_DATEINAME(
      "auswertung-jahrgangsstatistik-dateiname",
      "Auswertung Jahrgangsstatistik Dateiname",
      "Jahrgangsstatistik-$filter_jahr-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  AUSWERTUNG_ARBEITSEINSAETZE_DATEINAME("auswertung-arbeitseinsaetze-dateiname",
      "Auswertung Arbeitseinsätze Dateiname",
      "Arbeitseinsaetze-$filter_jahr-$filter_auswertung-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),

  // Reports aus Einstellungen Mitglieder
  BEITRAGSGRUPPEN_DATEINAME("beitragsgruppen-dateiname",
      "Beitragsgruppen Dateiname",
      "Beitragsgruppen-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  EIGENSCHAFTENGRUPPEN_DATEINAME("eigenschaftengruppen-dateiname",
      "Eigenschaftengruppen Dateiname",
      "Eigenschaftengruppen-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  EIGENSCHAFTEN_DATEINAME("eigenschaften-dateiname", "Eigenschaften Dateiname",
      "Eigenschaften-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  ZUSATZFELDER_DATEINAME("zusatzfelder-dateiname", "Zusatzfelder Dateiname",
      "Zusatzfelder-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  LESEFELDER_DATEINAME("lesefelder-dateiname", "Lesefelder Dateiname",
      "Lesefelder-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  FORMULARE_DATEINAME("formulare-dateiname", "Formulare Dateiname",
      "Formulare-$aktuellesdatum-$aktuellezeit", Vorlageart.DATEINAME.getKey()),
  LEHRGANGSARTEN_DATEINAME("lehrgangsarten-dateiname",
      "Lehrgangsarten Dateiname",
      "Lehrgangsarten-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  MITGLIEDSTYPEN_DATEINAME("mitgliedstypen-dateiname",
      "Mitgliedstypen Dateiname",
      "Mitgliedstypen-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),

  // Reports aus Einstellungen Buchführung
  BUCHUNGSARTEN_DATEINAME("buchungsarten-dateiname", "Buchungsarten Dateiname",
      "Buchungsarten-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  KONTENRAHMEN_DATEINAME_V1("kontenrahmen-v1-dateiname",
      "Kontenrahmen Version1 Dateiname",
      "Kontenrahmen-v1-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  KONTENRAHMEN_DATEINAME_V2("kontenrahmen-v2-dateiname",
      "Kontenrahmen Version2 Dateiname",
      "Kontenrahmen-v2-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  FORMULAR_DATEINAME("formular-dateiname", "Formular Dateiname",
      "Formular-$formular_name-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  FORMULARFELDER_DATEINAME("formularfelder-dateiname",
      "Formularfelder Dateiname",
      "Formularfelder-$formular_name-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  BUCHUNGSKLASSEN_DATEINAME("buchungsklassen-dateiname",
      "Buchungsklassen Dateiname",
      "Buchungsklassen-$aktuellesdatum-$aktuellezeit",
      Vorlageart.DATEINAME.getKey()),
  PROJEKTE_DATEINAME("projekte-dateiname", "Projekte Dateiname",
      "Projekte-$aktuellesdatum-$aktuellezeit", Vorlageart.DATEINAME.getKey()),
  STEUERN_DATEINAME("steuern-dateiname", "Steuern Dateiname",
      "Steuern-$aktuellesdatum-$aktuellezeit", Vorlageart.DATEINAME.getKey()),

  // Titel Mitglieder
  MITGLIEDER_TITEL("mitglieder-titel", "Mitglieder Titel", "Mitglieder",
      Vorlageart.TITEL.getKey()),
  MITGLIEDER_SUBTITEL("mitglieder-subtitel", "Mitglieder Subtitel", "",
      Vorlageart.TITEL.getKey()),
  NICHT_MITGLIEDER_TITEL("nichtmitglieder-titel", "Nicht-Mitglieder Titel",
      "Nicht-Mitglieder", Vorlageart.TITEL.getKey()),
  NICHT_MITGLIEDER_SUBTITEL("nichtmitglieder-subtitel",
      "Nicht-Mitglieder Subtitel", "", Vorlageart.TITEL.getKey()),
  MITGLIED_ZUSATZBETRAEGE_TITEL("mitglied-zusatzbetraege-titel",
      "Mitglied Zusatzbeträge Titel",
      "Zusatzbeträge $mitglied_vorname $mitglied_name",
      Vorlageart.TITEL.getKey()),
  MITGLIED_ZUSATZBETRAEGE_SUBTITEL("mitglied-zusatzbetraege-subtitel",
      "Mitglied Zusatzbeträge Subtitel", "", Vorlageart.TITEL.getKey()),
  MITGLIED_WIEDERVORLAGEN_TITEL("mitglied-wiedervorlagen-titel",
      "Mitglied Wiedervorlagen Titel",
      "Wiedervorlagen $mitglied_vorname $mitglied_name",
      Vorlageart.TITEL.getKey()),
  MITGLIED_WIEDERVORLAGEN_SUBTITEL("mitglied-wiedervorlagen-subtitel",
      "Mitglied Wiedervorlagen Subtitel", "", Vorlageart.TITEL.getKey()),
  MITGLIED_MAILS_TITEL("mitglied-mails-titel", "Mitglied Mails Titel",
      "Mails $mitglied_vorname $mitglied_name", Vorlageart.TITEL.getKey()),
  MITGLIED_MAILS_SUBTITEL("mitglied-mails-subtitel", "Mitglied Mails Subtitel",
      "", Vorlageart.TITEL.getKey()),
  MITGLIED_LEHRGAENGE_TITEL("mitglied-lehrgaenge-titel",
      "Mitglied Lehrgänge Titel", "Lehrgänge $mitglied_vorname $mitglied_name",
      Vorlageart.TITEL.getKey()),
  MITGLIED_LEHRGAENGE_SUBTITEL("mitglied-lehrgaenge-subtitel",
      "Mitglied Lehrgänge Subtitel", "", Vorlageart.TITEL.getKey()),
  MITGLIED_LESEFELDER_TITEL("mitglied-lesefelder-titel",
      "Mitglied Lesefelder Titel",
      "Lesefelder $mitglied_vorname $mitglied_name", Vorlageart.TITEL.getKey()),
  MITGLIED_LESEFELDER_SUBTITEL("mitglied-lesefelder-subtitel",
      "Mitglied Lesefelder Subtitel", "", Vorlageart.TITEL.getKey()),
  MITGLIED_ARBEITSEINSAETZE_TITEL("mitglied-arbeitseinsaetze-titel",
      "Mitglied Arbeitseinsätze Titel",
      "Arbeitseinsätze $mitglied_vorname $mitglied_name",
      Vorlageart.TITEL.getKey()),
  MITGLIED_ARBEITSEINSAETZE_SUBTITEL("mitglied-arbeitseinsaetze-subtitel",
      "Mitglied Arbeitseinsätze Subtitel", "", Vorlageart.TITEL.getKey()),
  MITGLIED_DOKUMENTE_TITEL("mitglied-dokumente-titel",
      "Mitglied Dokumente Titel", "Dokumente $mitglied_vorname $mitglied_name",
      Vorlageart.TITEL.getKey()),
  MITGLIED_DOKUMENTE_SUBTITEL("mitglied-dokumente-subtitel",
      "Mitglied Dokumente Subtitel", "", Vorlageart.TITEL.getKey()),
  KONTOAUSZUG_TITEL("kontoauszug-titel", "Kontoauszug Titel", "$verein_name",
      Vorlageart.TITEL.getKey()),
  KONTOAUSZUG_SUBTITEL("kontoauszug-subtitel", "Kontoauszug Subtitel",
      "Kontoauszug $mitglied_vornamename, Stand: $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$aktuellesdatum))",
      Vorlageart.TITEL.getKey()),

  // Reports aus Mitglieder
  PERSONALBOGEN_TITEL("personalbogen-titel", "Personalbogen Titel",
      "Personalbogen $mitglied_name $mitglied_vorname",
      Vorlageart.TITEL.getKey()),
  PERSONALBOGEN_SUBTITEL("personalbogen-subtitel", "Personalbogen Subtitel", "",
      Vorlageart.TITEL.getKey()),
  SPENDENBESCHEINIGUNGEN_TITEL("spendenbescheinigungen-titel",
      "Spendenbescheinigungen Titel", "Spendenbescheinigungen",
      Vorlageart.TITEL.getKey()),
  SPENDENBESCHEINIGUNGEN_SUBTITEL("spendenbescheinigungen-subtitel",
      "Spendenbescheinigungen Subtitel", "", Vorlageart.TITEL.getKey()),
  ARBEITSEINSAETZE_TITEL("arbeitseinsaetze-titel", "Arbeitseinsätze Titel",
      "Arbeitseinsätze", Vorlageart.TITEL.getKey()),
  ARBEITSEINSAETZE_SUBTITEL("arbeitseinsaetze-subtitel",
      "Arbeitseinsätze Subtitel", "", Vorlageart.TITEL.getKey()),
  ZUSATZBETRAEGE_VORLAGEN_TITEL("zusatzbetraege-vorlagen-titel",
      "Zusatzbeträge Vorlagen Titel", "Zusatzbeträge Vorlagen",
      Vorlageart.TITEL.getKey()),
  ZUSATZBETRAEGE_VORLAGEN_SUBTITEL("zusatzbetraege-vorlagen-subtitel",
      "Zusatzbeträge Vorlagen Subtitel", "", Vorlageart.TITEL.getKey()),
  ZUSATZBETRAEGE_TITEL("zusatzbetraege-titel", "Zusatzbeträge Titel",
      "Zusatzbeträge", Vorlageart.TITEL.getKey()),
  ZUSATZBETRAEGE_SUBTITEL("zusatzbetraege-subtitel", "Zusatzbeträge Subtitel",
      "", Vorlageart.TITEL.getKey()),
  LEHRGAENGE_TITEL("lehrgaenge-titel", "Lehrgänge Titel", "Lehrgänge",
      Vorlageart.TITEL.getKey()),
  LEHRGAENGE_SUBTITEL("lehrgaenge-subtitel", "Lehrgänge Subtitel", "",
      Vorlageart.TITEL.getKey()),
  KURSTEILNEHMER_TITEL("kursteilnehmer-titel", "Kursteilnehmer Titel",
      "Kursteilnehmer", Vorlageart.TITEL.getKey()),
  KURSTEILNEHMER_SUBTITEL("kursteilnehmer-subtitel", "Kursteilnehmer Subtitel",
      "", Vorlageart.TITEL.getKey()),
  RECHNUNGEN_TITEL("rechnungen-titel", "Rechnungen Titel", "Rechnungen",
      Vorlageart.TITEL.getKey()),
  RECHNUNGEN_SUBTITEL("rechnungen-subtitel", "Rechnungen Subtitel", "",
      Vorlageart.TITEL.getKey()),
  WIEDERVORLAGEN_TITEL("wiedervorlagen-titel", "Wiedervorlagen Titel",
      "Wiedervorlagen", Vorlageart.TITEL.getKey()),
  WIEDERVORLAGEN_SUBTITEL("wiedervorlagen-subtitel", "Wiedervorlagen Subtitel",
      "", Vorlageart.TITEL.getKey()),
  ABWEICHENDE_ZAHLER_TITEL("abweichende-zahler-titel",
      "Abweichende Zahler Titel", "Abweichende Zahler",
      Vorlageart.TITEL.getKey()),
  ABWEICHENDE_ZAHLER_SUBTITEL("abweichende-zahler-subtitel",
      "Abweichende Zahler Subtitel", "", Vorlageart.TITEL.getKey()),
  FAMILIENVERBAND_TITEL("familienverband-titel", "Familienverband Titel",
      "Familienverband", Vorlageart.TITEL.getKey()),
  FAMILIENVERBAND_SUBTITEL("familienverband-subtitel",
      "Familienverband Subtitel", "", Vorlageart.TITEL.getKey()),

  // Reports aus Buchführung
  KONTEN_TITEL("konten-titel", "Konten Titel", "Konten",
      Vorlageart.TITEL.getKey()),
  KONTEN_SUBTITEL("konten-subtitel", "Konten Subtitel", "",
      Vorlageart.TITEL.getKey()),
  ANFANGSBESTAENDE_TITEL("anfangsbestaende-titel", "Anfangsbestände Titel",
      "Anfangsbestände", Vorlageart.TITEL.getKey()),
  ANFANGSBESTAENDE_SUBTITEL("anfangsbestaende-subtitel",
      "Anfangsbestände Subtitel", "", Vorlageart.TITEL.getKey()),
  KONTENSALDO_TITEL("kontensaldo-titel", "Kontensaldo Titel", "Kontensaldo",
      Vorlageart.TITEL.getKey()),
  KONTENSALDO_SUBTITEL("kontensaldo-subtitel", "Kontensaldo Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_bis_f))",
      Vorlageart.TITEL.getKey()),
  BUCHUNGSJOURNAL_TITEL("buchungsjournal-titel", "Buchungsjournal Titel",
      "Buchungsjournal", Vorlageart.TITEL.getKey()),
  BUCHUNGSJOURNAL_SUBTITEL("buchungsjournal-subtitel",
      "Buchungsjournal Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$filter_datum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$filter_datum_bis_f))",
      Vorlageart.TITEL.getKey()),
  EINZELBUCHUNGEN_TITEL("einzelbuchungen-titel", "Einzelbuchungen Titel",
      "Buchungsliste", Vorlageart.TITEL.getKey()),
  EINZELBUCHUNGEN_SUBTITEL("einzelbuchungen-subtitel",
      "Einzelbuchungen Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$filter_datum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$filter_datum_bis_f))",
      Vorlageart.TITEL.getKey()),
  SUMMENBUCHUNGEN_TITEL("summenbuchungen-titel", "Summenbuchungen Titel",
      "Summenliste", Vorlageart.TITEL.getKey()),
  SUMMENBUCHUNGEN_SUBTITEL("summenbuchungen-subtitel",
      "Summenbuchungen Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$filter_datum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$filter_datum_bis_f))",
      Vorlageart.TITEL.getKey()),
  BUCHUNGEN_TITEL("buchungen-titel", "Buchungen Titel", "Buchungen",
      Vorlageart.TITEL.getKey()),
  BUCHUNGEN_SUBTITEL("buchungen-subtitel", "Buchungen Subtitel", "",
      Vorlageart.TITEL.getKey()),
  ANLAGEN_BUCHUNGSJOURNAL_TITEL("anlagen-buchungsjournal-titel",
      "Anlagen Buchungsjournal Titel", "Buchungsjournal",
      Vorlageart.TITEL.getKey()),
  ANLAGEN_BUCHUNGSJOURNAL_SUBTITEL("anlagen-buchungsjournal-subtitel",
      "Anlagen Buchungsjournal Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$filter_datum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$filter_datum_bis_f))",
      Vorlageart.TITEL.getKey()),
  ANLAGEN_EINZELBUCHUNGEN_TITEL("anlagen-einzelbuchungen-titel",
      "Anlagen Einzelbuchungen Titel", "Buchungsliste",
      Vorlageart.TITEL.getKey()),
  ANLAGEN_EINZELBUCHUNGEN_SUBTITEL("anlagen-einzelbuchungen-subtitel",
      "Anlagen Einzelbuchungen Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$filter_datum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$filter_datum_bis_f))",
      Vorlageart.TITEL.getKey()),
  ANLAGEN_SUMMENBUCHUNGEN_TITEL("anlagen-summenbuchungen-titel",
      "Anlagen Summenbuchungen Titel", "Summenliste",
      Vorlageart.TITEL.getKey()),
  ANLAGEN_SUMMENBUCHUNGEN_SUBTITEL("anlagen-summenbuchungen-subtitel",
      "Anlagen Summenbuchungen Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$filter_datum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$filter_datum_bis_f))",
      Vorlageart.TITEL.getKey()),
  ANLAGEN_BUCHUNGEN_TITEL("anlagen-buchungen-titel", "Anlagen Buchungen Titel",
      "Buchungen", Vorlageart.TITEL.getKey()),
  ANLAGEN_BUCHUNGEN_SUBTITEL("anlagen-buchungen-subtitel",
      "Anlagen Buchungen Subtitel", "", Vorlageart.TITEL.getKey()),
  BUCHUNGSKLASSENSALDO_TITEL("buchungsklassensaldo-titel",
      "Buchungsklassensaldo Titel", "Buchungsklassensaldo",
      Vorlageart.TITEL.getKey()),
  BUCHUNGSKLASSENSALDO_SUBTITEL("buchungsklassensaldo-subtitel",
      "Buchungsklassensaldo Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_bis_f))",
      Vorlageart.TITEL.getKey()),
  UMSATZSTEUER_VORANMELDUNG_TITEL("umsatzsteuervoranmeldung-titel",
      "Umsatzsteuer Voranmeldung Titel", "Umsatzsteuer Voranmeldung",
      Vorlageart.TITEL.getKey()),
  UMSATZSTEUER_VORANMELDUNG_SUBTITEL("umsatzsteuervoranmeldung-subtitel",
      "Umsatzsteuer Voranmeldung Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_bis_f))",
      Vorlageart.TITEL.getKey()),
  PROJEKTSALDO_TITEL("projektsaldo-titel", "Projektsaldo Titel", "Projektsaldo",
      Vorlageart.TITEL.getKey()),
  PROJEKTSALDO_SUBTITEL("projektsaldo-subtitel", "Projektsaldo Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_bis_f))",
      Vorlageart.TITEL.getKey()),
  ANLAGENVERZEICHNIS_TITEL("anlagenverzeichnis-titel",
      "Anlagenverzeichnis Titel", "Anlagenverzeichnis",
      Vorlageart.TITEL.getKey()),
  ANLAGENVERZEICHNIS_SUBTITEL("anlagenverzeichnis-subtitel",
      "Anlagenverzeichnis Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_bis_f))",
      Vorlageart.TITEL.getKey()),
  MITTELVERWENDUNGSREPORT_ZUFLUSS_TITEL("mittelverwendung-zufluss-titel",
      "Mittelverwendung Zuflussreport Titel", "Mittelverwendungsrechnung",
      Vorlageart.TITEL.getKey()),
  MITTELVERWENDUNGSREPORT_ZUFLUSS_SUBTITEL("mittelverwendung-zufluss-subtitel",
      "Mittelverwendung Zuflussreport Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_bis_f))",
      Vorlageart.TITEL.getKey()),
  MITTELVERWENDUNGSREPORT_SALDO_TITEL("mittelverwendung-saldo-titel",
      "Mittelverwendung Saldoreport Titel", "Mittelverwendungsrechnung",
      Vorlageart.TITEL.getKey()),
  MITTELVERWENDUNGSREPORT_SALDO_SUBTITEL("mittelverwendung-saldo-subtitel",
      "Mittelverwendung Saldoreport Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_bis_f))",
      Vorlageart.TITEL.getKey()),
  MITTELVERWENDUNGSSALDO_TITEL("mittelverwendungssaldo-titel",
      "Mittelverwendungssaldo Titel", "Mittelverwendungssaldo",
      Vorlageart.TITEL.getKey()),
  MITTELVERWENDUNGSSALDO_SUBTITEL("mittelverwendungssaldo-subtitel",
      "Mittelverwendungssaldo Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$zeitraum_bis_f))",
      Vorlageart.TITEL.getKey()),
  WIRTSCHAFTSPLAN_TITEL("wirtschaftsplan-titel", "Wirtschaftsplan Titel",
      "Wirtschaftsplan", Vorlageart.TITEL.getKey()),
  WIRTSCHAFTSPLAN_SUBTITEL("wirtschaftsplan-subtitel",
      "Wirtschaftsplan Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$parameter_datum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$parameter_datum_bis_f))",
      Vorlageart.TITEL.getKey()),
  WIRTSCHAFTSPLAN_MEHRERE_TITEL("wirtschaftsplan-mehrere-titel",
      "Wirtschaftsplan Titel (Mehrere Pläne)", "Wirtschaftsplan",
      Vorlageart.TITEL.getKey()),
  WIRTSCHAFTSPLAN_MEHRERE_SUBTITEL("wirtschaftsplan-mehrere-subtitel",
      "Wirtschaftsplan Subtitel (Mehrere Pläne)", "",
      Vorlageart.TITEL.getKey()),
  WIRTSCHAFTSPLAENE_TITEL("wirtschaftsplaene-titel", "Wirtschaftspläne Titel",
      "Wirtschaftspläne", Vorlageart.TITEL.getKey()),
  WIRTSCHAFTSPLAENE_SUBTITEL("wirtschaftsplaene-subtitel",
      "Wirtschaftspläne Subtitel", "", Vorlageart.TITEL.getKey()),
  JAHRESABSCHLUESSE_TITEL("jahresabschluesse-titel", "Jahresabschlüsse Titel",
      "Jahresabschlüsse", Vorlageart.TITEL.getKey()),
  JAHRESABSCHLUESSE_SUBTITEL("jahresabschluesse-subtitel",
      "Jahresabschlüsse Subtitel", "", Vorlageart.TITEL.getKey()),
  JAHRESABSCHLUSS_TITEL("jahresabschluss-titel", "Jahresabschluss Titel",
      "Jahresabschluss", Vorlageart.TITEL.getKey()),
  JAHRESABSCHLUSS_SUBTITEL("jahresabschluss-subtitel",
      "Jahresabschluss Subtitel",
      "$udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$filter_datum_von_f)) - $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$filter_datum_bis_f))",
      Vorlageart.TITEL.getKey()),
  SOLLBUCHUNGEN_TITEL("sollbuchungen-titel", "Sollbuchungen Titel",
      "Sollbuchungen", Vorlageart.TITEL.getKey()),
  SOLLBUCHUNGEN_SUBTITEL("sollbuchungen-subtitel", "Sollbuchungen Subtitel", "",
      Vorlageart.TITEL.getKey()),

  // Reports aus Abrechnung
  ABRECHNUNGSLAUF_LASTSCHRIFTEN2_TITEL("abrechnungslauf-lastschriften2-titel",
      "Abrechnungslauf Lastschriften Titel", "Abrechnungslauf Lastschriften",
      Vorlageart.TITEL.getKey()),
  ABRECHNUNGSLAUF_LASTSCHRIFTEN2_SUBTITEL(
      "abrechnungslauf-lastschriften2-subtitel",
      "Abrechnungslauf Lastschriften Subtitel",
      "Nr. $parameter_lauf zum $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$parameter_datum_f))",
      Vorlageart.TITEL.getKey()),
  ABRECHNUNGSLAUF_ZUSATZBETRAEGE_TITEL("abrechnungslauf-zusatzbetraege-titel",
      "Abrechnungslauf Zusatzbeträge Titel", "Abrechnungslauf Zusatzbeträge",
      Vorlageart.TITEL.getKey()),
  ABRECHNUNGSLAUF_ZUSATZBETRAEGE_SUBTITEL(
      "abrechnungslauf-zusatzbetraege-subtitel",
      "Abrechnungslauf Zusatzbeträge Subtitel",
      "Nr. $parameter_lauf zum $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$parameter_datum_f))",
      Vorlageart.TITEL.getKey()),
  ABRECHNUNGSLAUF_SOLLBUCHUNGEN_TITEL("abrechnungslaufliste-titel",
      "Abrechnungslauf Sollbuchungen Titel", "Abrechnungslauf Sollbuchungen",
      Vorlageart.TITEL.getKey()),
  ABRECHNUNGSLAUF_SOLLBUCHUNGEN_SUBTITEL("abrechnungslaufliste-subtitel",
      "Abrechnungslauf Sollbuchungen Subtitel",
      "Nr. $parameter_lauf zum $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$parameter_datum_f))",
      Vorlageart.TITEL.getKey()),
  ABRECHNUNGSLAUF_BUCHUNGEN_TITEL("abrechnungslauf-buchungen-titel",
      "Abrechnungslauf Buchungen Titel", "Abrechnungslauf Buchungen",
      Vorlageart.TITEL.getKey()),
  ABRECHNUNGSLAUF_BUCHUNGEN_SUBTITEL("abrechnungslauf-buchungen-subtitel",
      "Abrechnungslauf Buchungen Subtitel",
      "Nr. $parameter_lauf zum $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$parameter_datum_f))",
      Vorlageart.TITEL.getKey()),
  ABRECHNUNGSLAEUFE_TITEL("abrechnungslaeufe-titel", "Abrechnungsläufe Titel",
      "Abrechnungsläufe", Vorlageart.TITEL.getKey()),
  ABRECHNUNGSLAEUFE_SUBTITEL("abrechnungslaeufe-subtitel",
      "Abrechnungsläufe Subtitel", "", Vorlageart.TITEL.getKey()),
  LASTSCHRIFTEN_TITEL("lastschriften-titel", "Lastschriften Titel",
      "Lastschriften", Vorlageart.TITEL.getKey()),
  LASTSCHRIFTEN_SUBTITEL("lastschriften-subtitel", "Lastschriften Subtitel", "",
      Vorlageart.TITEL.getKey()),

  // Reports Druck und Mail
  MAILS_TITEL("mails-titel", "Mails Titel", "Mails", Vorlageart.TITEL.getKey()),
  MAILS_SUBTITEL("mails-subtitel", "Mails Subtitel", "",
      Vorlageart.TITEL.getKey()),
  MAILVORLAGEN_TITEL("mailvorlagen-titel", "Mailvorlagen Titel", "Mailvorlagen",
      Vorlageart.TITEL.getKey()),
  MAILVORLAGEN_SUBTITEL("mailvorlagen-subtitel", "Mailvorlagen Subtitel", "",
      Vorlageart.TITEL.getKey()),

  // Reports aus Auswertung
  AUSWERTUNG_MITGLIED_TITEL("auswertung-mitglied-titel",
      "Auswertung Mitglied Titel", "Mitglieder", Vorlageart.TITEL.getKey()),
  AUSWERTUNG_MITGLIED_SUBTITEL("auswertung-mitglied-subtitel",
      "Auswertung Mitglied Subtitel", "", Vorlageart.TITEL.getKey()),
  AUSWERTUNG_NICHT_MITGLIED_TITEL("auswertung-nichtmitglied-titel",
      "Auswertung Nicht-Mitglied Titel", "$filter_mitgliedstyp",
      Vorlageart.TITEL.getKey()),
  AUSWERTUNG_NICHT_MITGLIED_SUBTITEL("auswertung-nichtmitglied-subtitel",
      "Auswertung Nicht-Mitglied Subtitel", "", Vorlageart.TITEL.getKey()),
  AUSWERTUNG_ALTERSJUBILARE_TITEL("auswertung-altersjubilare-titel",
      "Auswertung Altersjubiläen Titel", "Altersjubilare $filter_jahr",
      Vorlageart.TITEL.getKey()),
  AUSWERTUNG_ALTERSJUBILARE_SUBTITEL("auswertung-altersjubilare-subtitel",
      "Auswertung Altersjubiläen Subtitel", "", Vorlageart.TITEL.getKey()),
  AUSWERTUNG_MITGLIEDSCHAFTSJUBILARE_TITEL(
      "auswertung-mitgliedsschaftsjubilare-titel",
      "Auswertung Mitgliedschaftsjubiläen Titel",
      "Mitgliedschaftsjubilare $filter_jahr", Vorlageart.TITEL.getKey()),
  AUSWERTUNG_MITGLIEDSCHAFTSJUBILARE_SUBTITEL(
      "auswertung-mitgliedsschaftsjubilare-subtitel",
      "Auswertung Mitgliedschaftsjubiläen Subtitel", "",
      Vorlageart.TITEL.getKey()),
  AUSWERTUNG_MITGLIEDER_STATISTIK_TITEL("auswertung-mitgliederstatistik-titel",
      "Auswertung Mitgliederstatistik Titel", "Mitgliederstatistik",
      Vorlageart.TITEL.getKey()),
  AUSWERTUNG_MITGLIEDER_STATISTIK_SUBTITEL(
      "auswertung-mitgliederstatistik-subtitel",
      "Auswertung Mitgliederstatistik Subtitel",
      "Stichtag: $udateformat.format(\"dd.MM.yyyy\",$udateformat.parse(\"yyyyMMdd\",$filter_stichtag_f))",
      Vorlageart.TITEL.getKey()),
  AUSWERTUNG_JAHRGANGS_STATISTIK_TITEL("auswertung-jahrgangsstatistik-titel",
      "Auswertung Jahrgangsstatistik Titel", "Jahrgangsstatistik",
      Vorlageart.TITEL.getKey()),
  AUSWERTUNG_JAHRGANGS_STATISTIK_SUBTITEL(
      "auswertung-jahrgangsstatistik-subtitel",
      "Auswertung Jahrgangsstatistik Subtitel", "Jahr: $filter_jahr",
      Vorlageart.TITEL.getKey()),
  AUSWERTUNG_ARBEITSEINSAETZE_TITEL("auswertung-arbeitseinsaetze-titel",
      "Auswertung Arbeitseinsätze Titel", "Arbeitseinsätze $filter_jahr",
      Vorlageart.TITEL.getKey()),
  AUSWERTUNG_ARBEITSEINSAETZE_SUBTITEL("auswertung-arbeitseinsaetze-subtitel",
      "Auswertung Arbeitseinsätze Subtitel", "$filter_auswertung",
      Vorlageart.TITEL.getKey()),

  // Reports aus Einstellungen Mitglieder
  BEITRAGSGRUPPEN_TITEL("beitragsgruppen-titel", "Beitragsgruppen Titel",
      "Beitragsgruppen", Vorlageart.TITEL.getKey()),
  BEITRAGSGRUPPEN_SUBTITEL("beitragsgruppen-subtitel",
      "Beitragsgruppen Subtitel", "", Vorlageart.TITEL.getKey()),
  EIGENSCHAFTENGRUPPEN_TITEL("eigenschaftengruppen-titel",
      "Eigenschaftengruppen Titel", "Eigenschaftengruppen",
      Vorlageart.TITEL.getKey()),
  EIGENSCHAFTENGRUPPEN_SUBTITEL("eigenschaftengruppen-subtitel",
      "Eigenschaftengruppen Subtitel", "", Vorlageart.TITEL.getKey()),
  EIGENSCHAFTEN_TITEL("eigenschaften-titel", "Eigenschaften Titel",
      "Eigenschaften", Vorlageart.TITEL.getKey()),
  EIGENSCHAFTEN_SUBTITEL("eigenschaften-subtitel", "Eigenschaften Subtitel", "",
      Vorlageart.TITEL.getKey()),
  ZUSATZFELDER_TITEL("zusatzfelder-titel", "Zusatzfelder Titel", "Zusatzfelder",
      Vorlageart.TITEL.getKey()),
  ZUSATZFELDER_SUBTITEL("zusatzfeldersubtitel", "Zusatzfelder Subtitel", "",
      Vorlageart.TITEL.getKey()),
  LESEFELDER_TITEL("lesefelder-titel", "Lesefelder Titel", "Lesefelder",
      Vorlageart.TITEL.getKey()),
  LESEFELDER_SUBTITEL("lesefeldersubtitel", "Lesefelder Subtitel", "",
      Vorlageart.TITEL.getKey()),
  FORMULARE_TITEL("formulare-titel", "Formulare Titel", "Formulare",
      Vorlageart.TITEL.getKey()),
  FORMULARE_SUBTITEL("formulare-subtitel", "Formulare Subtitel", "",
      Vorlageart.TITEL.getKey()),
  FORMULARFELDER_TITEL("formularfelder-titel", "Formularfleder Titel",
      "Formularfelder", Vorlageart.TITEL.getKey()),
  FORMULARFELDER_SUBTITEL("formularfelder-subtitel", "Formularfelder Subtitel",
      "", Vorlageart.TITEL.getKey()),
  LEHRGANGSARTEN_TITEL("lehrgangsarten-titel", "Lehrgangsarten Titel",
      "Lehrgangsarten", Vorlageart.TITEL.getKey()),
  LEHRGANGSARTEN_SUBTITEL("lehrgangsarten-subtitel", "Lehrgangsarten Subtitel",
      "", Vorlageart.TITEL.getKey()),
  MITGLIEDSTYPEN_TITEL("mitgliedstypen-titel", "Mitgliedstypen Titel",
      "Mitgliedstypen", Vorlageart.TITEL.getKey()),
  MITGLIEDSTYPEN_SUBTITEL("mitgliedstypen-subtitel", "Mitgliedstypen Subtitel",
      "", Vorlageart.TITEL.getKey()),

  // Reports aus Einstellungen Buchführung
  BUCHUNGSARTEN_TITEL("buchungsarten-titel", "Buchungsarten Titel",
      "Buchungsarten", Vorlageart.TITEL.getKey()),
  BUCHUNGSARTEN_SUBTITEL("buchungsarten-subtitel", "Buchungsarten Subtitel", "",
      Vorlageart.TITEL.getKey()),
  BUCHUNGSKLASSEN_TITEL("buchungsklassen-titel", "Buchungsklassen Titel",
      "Buchungsklassen", Vorlageart.TITEL.getKey()),
  BUCHUNGSKLASSEN_SUBTITEL("buchungsklassen-subtitel",
      "Buchungsklassen Subtitel", "", Vorlageart.TITEL.getKey()),
  PROJEKTE_TITEL("projekte-titel", "Projekte Titel", "Projekte",
      Vorlageart.TITEL.getKey()),
  PROJEKTE_SUBTITEL("projekte-subtitel", "Projekte Subtitel", "",
      Vorlageart.TITEL.getKey()),
  STEUERN_TITEL("steuern-titel", "Steuern Titel", "Steuern",
      Vorlageart.TITEL.getKey()),
  STEUERN_SUBTITEL("steuern-subtitel", "Steuern Subtitel", "",
      Vorlageart.TITEL.getKey());

  private final String text;

  private final String key;

  private final String defaultValue;

  private final int artKey;

  VorlageTyp(String key, String text, String defaultValue, int artKey)
  {
    this.key = key;
    this.text = text;
    this.defaultValue = defaultValue;
    this.artKey = artKey;
  }

  public String getKey()
  {
    return key;
  }

  public String getText()
  {
    return text;
  }

  public String getDefault()
  {
    return defaultValue;
  }

  public int getArtkey()
  {
    return artKey;
  }

  public static VorlageTyp getByKey(String key)
  {
    for (VorlageTyp art : VorlageTyp.values())
    {
      if (art.getKey().matches(key))
      {
        return art;
      }
    }
    return null;
  }

  @Override
  public String toString()
  {
    return getText();
  }
}
