# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: OpenJVerein build check

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    paths:
      - 'plugin.xml'
      - 'build/**'
      - 'lib/**'
      - 'lib.src/**'
      - 'src/**'
      - '.github/workflows/**/*.yml'
  push:
jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-build.yml

  build-check:
    needs: call-reusable-workflow
    runs-on: ubuntu-latest
    steps:
    - name: Checkout openjverein
      uses: actions/checkout@v4
      with:
        path: jverein

    - name: Restore build dependencies
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          jameica/bin/
          jameica/lib/**.jar
          jameica/releases/jameica-lib.jar
          hibiscus/bin/
          hibiscus/lib/**.jar
          hibiscus/releases/hibiscus-lib.jar
        fail-on-cache-miss: true
        key: ${{ hashFiles('jverein/build/build.properties', 'jverein/build/build.xml') }}

    - name: Build openjverein plugin
      working-directory: ./
      run: ant -noinput -buildfile jverein/build/build.xml compile
