# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: OpenJVerein build check

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    paths:
      - 'plugin.xml'
      - 'build/**'
      - 'lib/**'
      - 'lib.src/**'
      - 'src/**'
      - '.github/workflows/**/*.yml'
      - '.github/actions/**/*.yml'
  push:
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout openjverein
        uses: actions/checkout@v4

      - name: Restore cache
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository
          key: cache-${{ hashFiles('setup-build.xml') }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            cache-${{ hashFiles('setup-build.xml') }}

      - name: Build openjverein plugin
        run: ./mvnw --batch-mode --file pom.xml clean package

      - name: Save cache
        uses: actions/cache/save@v4
        if: steps.restore-cache.outputs.cache-hit != 'true'
        with:
          path: ~/.m2/repository
          key: cache-${{ hashFiles('setup-build.xml') }}-${{ hashFiles('**/pom.xml') }}
