# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: OpenJVerein build check

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    paths:
      - 'plugin.xml'
      - 'build/**'
      - 'lib/**'
      - 'lib.src/**'
      - 'src/**'
      - '.github/workflows/**/*.yml'
  push:
jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout openjverein
      uses: actions/checkout@v4

    - name: Setup
      uses: ./.github/build-dependencies/actions.yml

    - name: Build openjverein plugin
      run: ant -noinput -buildfile build/build.xml compile
