# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: OpenJVerein nightly release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout openjverein
        uses: actions/checkout@v4

      - name: Setup
        uses: .github/actions/build-dependencies

      - name: Build openjverein plugin
        id: openjverein
        run: |
          ./mvnw --batch-mode --file pom.xml clean package
          tmp_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "selected_version=${tmp_version}" >> $GITHUB_OUTPUT

      # Update tag
      - name: Tag repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ steps.openjverein.outputs.selected_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.openjverein.outputs.selected_version }}
          prerelease: true
          name: Release ${{ steps.openjverein.outputs.selected_version }}
          files: ./target/jverein-*.zip
          generate_release_notes: false
